apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hls-segments
  namespace: recorder
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE}
