apiVersion: v1
kind: Service
metadata:
  name: hls-ring-recorder
  namespace: recorder
spec:
  type: NodePort
  selector:
    app: hls-ring-recorder
  ports:
  - name: nginx
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: ntfy
    port: 80
    targetPort: 80
    nodePort: 30081
